version: '2.1'

orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
    - image: circleci/ruby:2.5.7-stretch-node
    - image: circleci/ruby:2.6.5-stretch-node
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: test
          command: bundle exec rake test
